name = "SummaryTablesExtras"
uuid = "b1e5a2b9-85de-45c7-a260-4d8dda977783"
authors = ["simonsteiger <simon.j.steiger@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
SummaryTables = "6ce4ecf0-73a7-4ce3-9fb4-80ebfe887b60"

[compat]
DataFrames = "1"
SummaryTables = "3.5.1"
julia = "1.10"

[extras]
ReferenceTests = "3d0afe11-e35d-4a68-ac66-17789b0f6f47"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["ReferenceTests", "Test"]
